// Departamentos de Colombia
export const DEPARTAMENTOS_COLOMBIA = [
    'Amazonas',
    'Antioquia',
    'Arauca',
    'Atlántico',
    'Bolívar',
    'Boyacá',
    'Caldas',
    'Caquetá',
    'Casanare',
    'Cauca',
    'Cesar',
    'Chocó',
    'Córdoba',
    'Cundinamarca',
    'Guainía',
    'Guaviare',
    'Huila',
    'La Guajira',
    'Magdalena',
    'Meta',
    'Nariño',
    'Norte de Santander',
    'Putumayo',
    'Quindío',
    'Risaralda',
    'San Andrés y Providencia',
    'Santander',
    'Sucre',
    'Tolima',
    'Valle del Cauca',
    'Vaupés',
    'Vichada'
]

// Ciudades y Municipios por Departamento
export const CIUDADES_PRINCIPALES: Record<string, string[]> = {
    'Amazonas': ['Leticia', 'Puerto Nariño'],
    'Antioquia': ['Medellín', 'Envigado', 'Itagüí', 'Bello', 'Rionegro', 'Sabaneta', 'La Estrella', 'Caldas', 'Apartadó', 'Caucasia', 'Copacabana', 'Girardota', 'Marinilla', 'Turbo'],
    'Arauca': ['Arauca', 'Arauquita', 'Saravena', 'Tame'],
    'Atlántico': ['Barranquilla', 'Soledad', 'Malambo', 'Puerto Colombia', 'Sabanalarga', 'Galapa', 'Baranoa'],
    'Bolívar': ['Cartagena', 'Magangué', 'Turbaco', 'Arjona', 'El Carmen de Bolívar'],
    'Boyacá': ['Tunja', 'Duitama', 'Sogamoso', 'Chiquinquirá', 'Paipa', 'Puerto Boyacá', 'Moniquirá'],
    'Caldas': ['Manizales', 'Villamaría', 'Chinchiná', 'La Dorada', 'Riosucio'],
    'Caquetá': ['Florencia', 'San Vicente del Caguán', 'Puerto Rico'],
    'Casanare': ['Yopal', 'Aguazul', 'Villanueva', 'Monterrey', 'Paz de Ariporo'],
    'Cauca': ['Popayán', 'Santander de Quilichao', 'Puerto Tejada', 'Piendamó', 'El Bordo'],
    'Cesar': ['Valledupar', 'Aguachica', 'Bosconia', 'La Jagua de Ibirico', 'Codazzi'],
    'Chocó': ['Quibdó', 'Istmina', 'Condoto', 'Tadó'],
    'Córdoba': ['Montería', 'Cereté', 'Lorica', 'Sahagún', 'Montelíbano', 'Planeta Rica'],
    'Cundinamarca': ['Bogotá', 'Soacha', 'Facatativá', 'Zipaquirá', 'Chía', 'Mosquera', 'Fusagasugá', 'Madrid', 'Funza', 'Cajicá', 'Girardot', 'Villeta', 'La Mesa'],
    'Guainía': ['Inírida'],
    'Guaviare': ['San José del Guaviare', 'Calamar'],
    'Huila': ['Neiva', 'Pitalito', 'Garzón', 'La Plata', 'Campoalegre'],
    'La Guajira': ['Riohacha', 'Maicao', 'Uribia', 'Manaure', 'Fonseca', 'Barrancas'],
    'Magdalena': ['Santa Marta', 'Ciénaga', 'Fundación', 'El Banco', 'Plato'],
    'Meta': ['Villavicencio', 'Acacías', 'Granada', 'Puerto López', 'Restrepo', 'Cumaral'],
    'Nariño': ['Pasto', 'Tumaco', 'Ipiales', 'Túquerres', 'La Unión'],
    'Norte de Santander': ['Cúcuta', 'Ocaña', 'Pamplona', 'Villa del Rosario', 'Los Patios', 'Tibú'],
    'Putumayo': ['Mocoa', 'Puerto Asís', 'Sibundoy', 'Orito', 'Villagarzón'],
    'Quindío': ['Armenia', 'Calarcá', 'La Tebaida', 'Montenegro', 'Quimbaya', 'Circasia'],
    'Risaralda': ['Pereira', 'Dosquebradas', 'Santa Rosa de Cabal', 'La Virginia', 'Belén de Umbría'],
    'San Andrés y Providencia': ['San Andrés', 'Providencia'],
    'Santander': ['Bucaramanga', 'Floridablanca', 'Girón', 'Piedecuesta', 'Barrancabermeja', 'San Gil', 'Socorro', 'Vélez'],
    'Sucre': ['Sincelejo', 'Corozal', 'Sampués', 'San Marcos', 'Tolú'],
    'Tolima': ['Ibagué', 'Espinal', 'Melgar', 'Honda', 'Mariquita', 'Líbano', 'Chaparral'],
    'Valle del Cauca': ['Cali', 'Palmira', 'Buenaventura', 'Tuluá', 'Yumbo', 'Buga', 'Cartago', 'Jamundí', 'Candelaria', 'Florida', 'Pradera'],
    'Vaupés': ['Mitú'],
    'Vichada': ['Puerto Carreño']
}

// Categorías de repuestos
export const CATEGORIAS_REPUESTOS = [
    'Frenos',
    'Motor',
    'Suspensión',
    'Transmisión',
    'Eléctrico',
    'Carrocería',
    'Neumáticos y Llantas',
    'Lubricantes y Fluidos',
    'Sistema de Escape',
    'Sistema de Refrigeración',
    'Filtros',
    'Iluminación',
    'Pintura/Latonería',
    'Otros'
]
